- type: replace
  path: /instance_groups/name=alertmanager/vm_type
  value: ((vm_type_micro))

- type: replace
  path: /instance_groups/name=prometheus/vm_type
  value: ((vm_type_small))

- type: replace
  path: /instance_groups/name=database/vm_type
  value: ((vm_type_small))

- type: replace
  path: /instance_groups/name=grafana/vm_type
  value: ((vm_type_small))

- type: replace
  path: /instance_groups/name=nginx/vm_type
  value: ((vm_type_micro))

- type: replace
  path: /instance_groups/name=firehose/vm_type
  value: ((vm_type_small))

- type: replace
  path: /instance_groups/name=alertmanager/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=prometheus/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=database/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=grafana/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=nginx/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=firehose/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=alertmanager/azs
  value: ((azs))

- type: replace
  path: /instance_groups/name=prometheus/azs
  value: ((azs))

- type: replace
  path: /instance_groups/name=database/azs
  value: ((azs))

- type: replace
  path: /instance_groups/name=grafana/azs
  value: ((azs))

- type: replace
  path: /instance_groups/name=nginx/azs
  value: ((azs))

- type: replace
  path: /instance_groups/name=firehose/azs
  value: ((azs))