---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: pcf-prometheus-pipeline

params:
  opsman_url:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  uaa_bosh_exporter_client_secret:
  uaa_clients_firehose_exporter_secret:
  uaa_clients_cf_exporter_secret:

run:
  path: pcf-prometheus-pipeline/pipeline/tasks/create-uaa-clients.sh
