---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker-gcp

inputs:
- name: pcf-prometheus-git

params:
  pcf_ert_domain:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  pcf_sys_domain:
  prometheus_bosh_client:
  prometheus_bosh_secret:
  prometheus_firehose_client:
  prometheus_firehose_secret:
  prometheus_cf_client:
  prometheus_cf_secret:
  opsman_url:

run:
  path: pcf-prometheus-git/pipeline/tasks/create-uaa-creds.sh
