---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker-gcp

inputs:
- name: om-bosh-creds
- name: pcf-prometheus-git

params:
  prometheus_bosh_client:
  prometheus_bosh_secret:
  prometheus_firehose_client:
  prometheus_firehose_secret:
  prometheus_cf_client:
  prometheus_cf_secret:
  azs:
  network_name:
  vm_password:
  vm_type_micro:
  vm_type_small:
  nginx_ip:
  pcf_sys_domain:
  pcf_ert_domain:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  opsman_url:
  nats_machines:
  nats_username:
  nats_password:
  grafana_admin_password:

run:
  path: pcf-prometheus-git/pipeline/tasks/deploy.sh
