---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ramxx/cfjump

inputs:
- name: pcf-prometheus-git
- name: pcf-bosh-creds

run:
  path: pcf-prometheus-git/pipeline/tasks/install-node-exporter.sh
