---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: pcf-prometheus-pipeline

outputs:
- name: dynamic-params

params:
  opsman_url:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:

run:
  path: pcf-prometheus-pipeline/pipeline/tasks/retrieve-params-from-opsman.sh
