---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker-gcp

inputs:
- name: pcf-prometheus-git
- name: om-bosh-creds
- name: prometheus-release
- name: node-exporter-release

run:
  path: pcf-prometheus-git/pipeline/tasks/upload-release.sh
