---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cpi-certification

inputs:
- name: pcf-prometheus-git
- name: pcf-bosh-creds
- name: node-exporter-release

run:
  path: pcf-prometheus-git/pipeline/tasks/upload-release.sh
